/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        'sf-pro': ['"SF Pro Display"', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'sans-serif'],
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: 'none',
            color: '#374151',
            lineHeight: '1.4',
            fontFamily: '"SF Pro Display", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
            p: {
              marginTop: '0.3em',
              marginBottom: '0.3em',
              fontFamily: '"SF Pro Display", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
            },
            h1: {
              fontFamily: '"SF Pro Display", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
              fontWeight: '700',
              marginBottom: '0.5em',
            },
            h2: {
              fontFamily: '"SF Pro Display", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
              fontWeight: '600',
              marginTop: '1em',
              marginBottom: '0.4em',
            },
            h3: {
              fontFamily: '"SF Pro Display", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
              fontWeight: '600',
              marginTop: '0.8em',
              marginBottom: '0.3em',
            },
            h4: {
              fontFamily: '"SF Pro Display", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
              fontWeight: '600',
              marginTop: '0.7em',
              marginBottom: '0.3em',
            },
            li: {
              fontFamily: '"SF Pro Display", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
              marginBottom: '0.2em',
            },
            '--tw-prose-body': '#374151',
            '--tw-prose-headings': '#111827',
            '--tw-prose-lead': '#4B5563',
            '--tw-prose-links': '#3B82F6',
            '--tw-prose-bold': '#111827',
            '--tw-prose-counters': '#6B7280',
            '--tw-prose-bullets': '#D1D5DB',
            '--tw-prose-hr': '#E5E7EB',
            '--tw-prose-quotes': '#111827',
            '--tw-prose-quote-borders': '#E5E7EB',
            '--tw-prose-captions': '#6B7280',
            '--tw-prose-code': '#111827',
            '--tw-prose-pre-code': '#E5E7EB',
            '--tw-prose-pre-bg': '#1F2937',
            '--tw-prose-th-borders': '#D1D5DB',
            '--tw-prose-td-borders': '#E5E7EB',
            '--tw-prose-invert-body': '#D1D5DB',
            '--tw-prose-invert-headings': '#FFFFFF',
            '--tw-prose-invert-lead': '#9CA3AF',
            '--tw-prose-invert-links': '#60A5FA',
            '--tw-prose-invert-bold': '#FFFFFF',
            '--tw-prose-invert-counters': '#9CA3AF',
            '--tw-prose-invert-bullets': '#4B5563',
            '--tw-prose-invert-hr': '#374151',
            '--tw-prose-invert-quotes': '#F3F4F6',
            '--tw-prose-invert-quote-borders': '#374151',
            '--tw-prose-invert-captions': '#9CA3AF',
            '--tw-prose-invert-code': '#FFFFFF',
            '--tw-prose-invert-pre-code': '#D1D5DB',
            '--tw-prose-invert-pre-bg': '#00000066',
            '--tw-prose-invert-th-borders': '#4B5563',
            '--tw-prose-invert-td-borders': '#374151',
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
